version: '2.0'
services:
    zoneminder:
        container_name: zoneminder
        image: dlandon/zoneminder:latest
        restart: unless-stopped
        ports:
            - 8443:443/tcp
            - 3030:9000/tcp
        network_mode: "bridge"
        privileged: true
        environment:
            - TZ=Asia/Jerusalem
            - SHMEM=50%
            - PUID=99
            - PGID=100
            - INSTALL_HOOK=1
            - INSTALL_FACE=1
            - INSTALL_TINY_YOLOV3=0
            - INSTALL_YOLOV3=0
            - INSTALL_TINY_YOLOV4=1
            - INSTALL_YOLOV4=0
            - MULTI_PORT_START=0
            - MULTI_PORT_END=0
        volumes:
            - config:/config:rw
            - data:/var/cache/zoneminder:rw
volumes:
    config:
    data:
